name: watching
description: "Keep track of all your watching."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.4
  hive: ^2.2.3
  http: ^1.2.1
  logger: ^2.2.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - dotEnv.stage
  - dotEnv.dev
  - dotEnv.prod
