// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['webApiKey']!,
    appId: dotenv.env['webAppId']!,
    messagingSenderId: dotenv.env['messagingSenderId']!,
    projectId: dotenv.env['projectId']!,
    authDomain: dotenv.env['authDomain']!,
    storageBucket: dotenv.env['storageBucket']!,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidApiKey']!,
    appId: dotenv.env['androidAppId']!,
    messagingSenderId: dotenv.env['messagingSenderId']!,
    projectId: dotenv.env['projectId']!,
    storageBucket: dotenv.env['storageBucket']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['iosApiKey']!,
    appId: dotenv.env['iosAppId']!,
    messagingSenderId: dotenv.env['messagingSenderId']!,
    projectId: dotenv.env['projectId']!,
    storageBucket: dotenv.env['storageBucket']!,
    iosClientId: dotenv.env['iosClientId']!,
    iosBundleId: dotenv.env['iosBundleId']!,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8rcAHR_h4HrrFthUwRZUgZpOFJHqsuVU',
    appId: '1:943566948341:ios:fa708d5438764166a402bc',
    messagingSenderId: '943566948341',
    projectId: 'watching-development',
    storageBucket: 'watching-development.appspot.com',
    iosClientId:
        '943566948341-q9gsi9qh77htgtjf4r3fufrb8q9lemti.apps.googleusercontent.com',
    iosBundleId: 'com.example.watching',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: 'watching-development',
    authDomain: 'watching-development.firebaseapp.com',
    storageBucket: 'watching-development.appspot.com',
  );
}
